### ISSUE TITLE
`--output-dir` option not compatible with older curl versions

### ISSUE THREAD

**Issue by gcanat** [girishji/devdocs.vim#12]
On Ubuntu 20.04, latest curl version is 7.68.0, which does not support `--output-dir`. This causes an issue when trying to download docs ( line 80 of `install.vim`).

Solution:
```diff
-        $'curl -fsSL --remote-name-all --output-dir {tmpdir} --create-dirs "{url}"',
+        $'curl -fsSL --remote-name-all -o "{tmpdir}/#1.json" --create-dirs "{url}"',
```

`#1` will match `{{index,db}}` from `{url}`

**Comment by girishji** [comment]
Just a thought: You could clone the repo and make the change locally. I am thinking this is a temporary issue and you'll upgrade Ubuntu eventually.

**Comment by gcanat** [comment]
Fair enough :smile:
