### ISSUE TITLE
add filter key <C-c> to close popup like <Esc>

### ISSUE THREAD

**Issue by Song-Tianxiang** [girishji/devdocs.vim#3]
vim's native way to close popup is `<C-c>`, but our popup have two parts. Now `<C-c>` gives me: 
<img width="1259" alt="Screenshot 2024-03-09 at 19 05 51" src="https://github.com/girishji/devdocs.vim/assets/149415622/312743ec-98dd-4b4d-a4c6-8ea75f53d2de">

Please add filter key `<C-c>` to close both two popup like `<Esc>` key

**Comment by girishji** [comment]
Absolutely. I fixed it now. please try.
